---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  namespace: guestbook
  name: redis-follower-app-placement-1
  labels:
    app: redis-follower-app
spec:
  clusterSelector:
    matchLabels:
      name: aws-cluster

