---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  namespace: guestbook
  name: redis-follower-app-subscription-1
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: redis-follower-app/redis-follower
  labels:
    app: redis-follower-app
spec:
  channel: guestbook/redis-follower-app-latest
  placement:
    placementRef:
      name: redis-follower-app-placement-1
      kind: PlacementRule
