---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: redis-leader-app-latest
  namespace: guestbook
spec:
  type: GitHub
  pathname: https://github.com/hariwi/acm-demo-app.git
