---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  namespace: guestbook
  name: redis-leader-app-placement-1
  labels:
    app: redis-leader-app
spec:
  clusterSelector:
    matchLabels:
      name: aws-cluster-2

