---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  namespace: guestbook
  name: redis-leader-app-subscription-1
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: redis-leader-app/redis-leader
  labels:
    app: redis-leader-app
spec:
  channel: guestbook/redis-leader-app-latest
  placement:
    placementRef:
      name: redis-leader-app-placement-1
      kind: PlacementRule
